### ISSUE TITLE
Refreshing image when bound URL changes

### ISSUE THREAD

**Issue by arctic-studio** [dmytro-anokhin/url-image-demo#1]
Hi,

Thanks for developing URLImage, it's really helpful and very flexible.
However, if I bind the url to a state variable, the image does not refresh when the URL changes. Is there a way to achieve this please?

JP

**Comment by dmytro-anokhin** [comment]
Hey, please open an issue in the package issue tracker (https://github.com/dmytro-anokhin/url-image/issues) using Bug report template. Also make sure to submit a sample code to reproduce the bug. Thank you.
