### ISSUE TITLE
Exporting an URLImage

### ISSUE THREAD

**Issue by alelordelo** [dmytro-anokhin/url-image-demo#2]
Hi Dmytro, thanks for such a high caliber package! : )

I am trying to export an  URLImage, using the new SwiftUI .fileExporter modifier.

The setup bellow works for a conventional UIImage, but I haven't fired out how to make it work for URLImage, and I get the error bellow:

_Type 'Bundle?' has no member 'jpeg'_

Super appreciate if you could help with an example on how to export the images!

Cheers from Stockholm

```
        //file exporter
    
        .fileExporter(isPresented: $exportFile, document: ImageDocument(
                        
                        
                        image: UIImage( URLImage(URL(string: fabric.mediaUrl)!)!
                       // image2:  UIImage( URLImage(URL(string: fabric.mediaUrl)!)
                      
                      ,
               
    contentType: .jpeg, onCompletion: { (result) in
        
                if case .success = result {
                
                    print("Success")
                } else {
                    print("Failure")
                }
            })
        

        
        
    }
}

//document directory
func documentDirectoryPath() -> URL? {
    let path = FileManager.default.urls(for: .documentDirectory,
                                        in: .userDomainMask)
    return path.first
}


//export group of images
struct ImageDocument: FileDocument {
    
    static var readableContentTypes: [UTType] { [.jpeg] }

    var image: UIImage
   // var image2: UIImage


    init(
        image: UIImage?
      //  image2: UIImage?
    ) {
        
        self.image = image ?? UIImage()
      //  self.image2 = image2 ?? UIImage()

    }

    init(configuration: ReadConfiguration) throws {
        guard let data = configuration.file.regularFileContents,
              let image = UIImage(data: data)
          //    let image2 = UIImage(data: data)

        else {
            throw CocoaError(.fileReadCorruptFile)
        }
        self.image = image
     //   self.image2 = image2

    }
    
    
//wrap files
    func fileWrapper(configuration: WriteConfiguration) throws -> FileWrapper {
        
        let export = image.jpegData(compressionQuality: 0.80)!; image.jpegData(compressionQuality: 0.80)!

        return FileWrapper(regularFileWithContents:
                            export
                           // image1.jpegData(compressionQuality: 0.80)!,
                           // image2.jpegData(compressionQuality: 0.80)! //<----- getting an "extra argument error here
        
                            )
    }
    
}

```

**Comment by dmytro-anokhin** [comment]
Hey,

thanks for using `URLImage`, but I have to disappoint you - `URLImage` is a view, it does not represent a file that you can export.

There is a way to access underlying `CGImage` using `ImageInfo` object. There's additional initialiser for that: [Image Information](https://github.com/dmytro-anokhin/url-image#image-information). Make sure to set `maxPixelSize` to `nil` to get the original image.

This, however, is not an optimal way, because the image will be decoded and encoded in memory, so I would avoid it for large images.

I will keep in mind your use case for further development of the package.

**Comment by alelordelo** [comment]
thanks for helping @dmytro-anokhin! 

I tried the init bellow, but wasn't able to make it work with ImageDocument.

Do you have any idea how I could pass the image to the exporter?


    init(url: URL, content: @escaping (_ image: Image, _ info: ImageInfo) -> Content)

**Comment by dmytro-anokhin** [comment]
I just realised that you're not using the view. In this case you can use `RemoteImagePublisher` as described here: [fetching an image](https://github.com/dmytro-anokhin/url-image#fetching-an-image):

```
cancellable = URLImageService.shared.remoteImagePublisher(url)
    .tryMap { $0.cgImage }
    .catch { _ in
        Just(nil)
    }
    .sink { image in
        // image is CGImage or nil
    }
```

This is of course asynchronous operation, so you first need to wait till it completes, then you can serialise the image.

**Comment by alelordelo** [comment]
Hi @dmytro-anokhin, I made an demo app "URL Image Export".
Due to my limitation on how remote Images work in SwiftUI, I cannot figure out how to export it...

Any input is highly appreciated! : )
Happy to donate via PayPal or any other method if you can give a hand on this

```
import SwiftUI
import Combine
import URLImage
import UniformTypeIdentifiers

struct ContentView: View {
    
    @State private var exportFile = false

    let url = "https://media.wired.com/photos/5b8999943667562d3024c321/master/w_2560%2Cc_limit/trash2-01.jpg"

    var body: some View {
        
        NavigationView {

        
        // image to be exported
            URLImage(url: URL(string: url)!,
                 content: { image in
                           image
        .renderingMode(.original)
        .resizable()
        .frame(width: 48, height: 48)
                                      })
        
        
                .navigationTitle("URL Image Exporter")

                .toolbar {

                    ToolbarItemGroup(placement: .primaryAction) {

                        //export button
                        Button(
                           action: {
                            self.exportFile.toggle() }) {
                            Image(systemName: "square.and.arrow.up")
                        }
                    }
                }
                
                
            //download an image as CGImage and ignore any errors
            //not sure what to do here
        var cancellable = URLImageService.shared.remoteImagePublisher(url)
                            .tryMap { $0.cgImage }
                            .catch { _ in
                                Just(nil)
                            }
                            .sink { image in
                                // image is CGImage or nil
                            }
            
            //file exporter
          .fileExporter(isPresented: $exportFile, document: ImageDocument(

                            image: UIImage( URLImage(URL(string: url)!)!
                          ,

        contentType: .jpeg, onCompletion: { (result) in

                    if case .success = result {

                        print("Success")
                    } else {
                        
                        print("Failure")
                    }
                })
        
        }
    }
    
    
    //document directory
    func documentDirectoryPath() -> URL? {
        let path = FileManager.default.urls(for: .documentDirectory,
                                            in: .userDomainMask)
        return path.first
    }

   
    //export images
    struct ImageDocument: FileDocument {
        
        
        static var readableContentTypes: [UTType] { [.jpeg] }

        var image: UIImage
       // var image2: UIImage


        init(
            image: UIImage?
          //  image2: UIImage?
        ) {
            
            self.image = image ?? UIImage()
          //  self.image2 = image2 ?? UIImage()

        }

        init(configuration: ReadConfiguration) throws {
            guard let data = configuration.file.regularFileContents,
                  let image = UIImage(data: data)
              //    let image2 = UIImage(data: data)

            else {
                throw CocoaError(.fileReadCorruptFile)
            }
            self.image = image
         //   self.image2 = image2

        }
        
        
    //wrap files
        func fileWrapper(configuration: WriteConfiguration) throws -> FileWrapper {
            
            let export = image.jpegData(compressionQuality: 0.80)!; image.jpegData(compressionQuality: 0.80)!

            return FileWrapper(regularFileWithContents:
                                export
                               // image1.jpegData(compressionQuality: 0.80)!,
                               // image2.jpegData(compressionQuality: 0.80)! //<----- getting an "extra argument error here
            
                                )
        }
        
    
    
}
    
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}

```

**Comment by dmytro-anokhin** [comment]
Hey, check [ImageDownloader](https://github.com/dmytro-anokhin/url-image-demo/tree/main/ImageDownloader) folder in the sample app repo. Hope it helps. Cheers.

**Comment by alelordelo** [comment]
Ok,fixed now after installing SPM via SwiftUi branch…

Thanks!

**Comment by alelordelo** [comment]
Hey @dmytro-anokhin , massive thanks for that! : )

Working perfect on ContentView. However when I put same code inside another view ( ex: ContentView -> AnotherView), the image doesn't load. ..Any idea why?

**Comment by alelordelo** [comment]
Thanks so much man! After a couple hours figuring out the "allow arbitrary loads", working fine now!  : )

**Comment by alelordelo** [comment]
hi @dmytro-anokhin ,

I am trying to pass the URL from another view, but got this error:

_"Cannot use instance member 'post' within property initializer; property initializers run before 'self' is available"_
    
  Any idea what could be wrong?


struct Export: View {
    
   
    var post: Post

    let url =  URL(string: post.mediaUrl)!


    init() {
        model = Model(url: url)
    }


    


    var body: some View {
        
        
        let url =  URL(string: post.mediaUrl)!

        
       NavigationView {
            
            Form {
                

            //image 1
            URLImage(url: model.url) {
                $0.resizable()
                    .aspectRatio(contentMode: .fit)
            }
            
            .onAppear {
                model.load()
                
            }
                
                
            }
            .navigationTitle(url.absoluteString)
            .toolbar {
                ToolbarItemGroup(placement: .primaryAction) {
                    // Show export button only if the image is downloaded
                    if model.isLoaded {
                        Button(action: {
                            isFileExportPresented.toggle()
                        }) {
                            Image(systemName: "square.and.arrow.up")
                        }
                    }
                }
            }
            .fileExporter(isPresented: $isFileExportPresented, document: model.document, contentType: .jpeg) {
                // TODO: Handle the result
                print($0)
            }
          }
        .navigationViewStyle(StackNavigationViewStyle())
    }

    /// State of file export dialog presentation
    @State  var isFileExportPresented = false

    @ObservedObject var model: Model
}

**Comment by dmytro-anokhin** [comment]
Hey, basically what compiler is saying, I can't think about expressing it better myself 🙂 If you're having troubles with initialization in Swift, best resource is the swift programming language guide: https://docs.swift.org/swift-book/LanguageGuide/Initialization.html
